apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: juliocesarmidia/api:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: api-port
              containerPort: 9000
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: api-port
            initialDelaySeconds: 10
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: api-port
            initialDelaySeconds: 10
            timeoutSeconds: 30
          env:
            - name: API_PORT
              value: "9000"
            - name: MESSAGE
              value: "Golang API"
          resources:
            requests:
              memory: "128Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "300m"

      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: default
  labels:
    component: api
spec:
  type: ClusterIP
  selector:
    component: api
  ports:
  - port: 80
    name: http
    targetPort: api-port
    protocol: TCP

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  namespace: default
  labels:
    release: prometheus-operator
    component: api
spec:
  selector:
    matchLabels:
      component: api
  namespaceSelector:
    any: true
    # matchNames:
    # - default
  endpoints:
  - port: http
    interval: 15s
    # path: "/metrics"
