version: "3.4"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    command: [
      "--config.file=/prometheus-config/prometheus.yaml",
      "--web.config.file=/prometheus-config/web.yaml"
    ]
    volumes:
      - ./prometheus/:/prometheus-config
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    networks:
      - subnet_0
    restart: on-failure

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning/
    ports:
      - 3000:3000
    networks:
      - subnet_0
    restart: on-failure

  api:
    container_name: api
    build:
      context: ./api
    ports:
      - 9000:9000
    networks:
      - subnet_0
    restart: on-failure
    # healthcheck:
    #   test: "curl -sS http://api:9000/healthcheck"
    #   interval: 10s
    #   timeout: 30s
    #   retries: 60

networks:
  subnet_0:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/24"

volumes:
  prometheus-data: {}
  grafana-data: {}
