version: "3.4"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    command: ["--config.file=/prometheus-config/prometheus.yaml"]
    volumes:
      - ./prometheus/:/prometheus-config
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    networks:
      - subnet_0
    restart: on-failure

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning/
    ports:
      - 3300:3000
    networks:
      - subnet_0
    restart: on-failure

  api:
    container_name: api
    build:
      context: ./api
    ports:
      - 9000:9000
    networks:
      - subnet_0
    restart: on-failure

networks:
  subnet_0:
    driver: bridge

volumes:
  prometheus-data: {}
  grafana-data: {}
