global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - localhost:9090

    basic_auth:
      username: admin
      password: admin

  - job_name: api
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
    - targets:
      - api:9000
